modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://github.com/Mrbysco/BlockHistory/issues"
license="MIT"

[[mods]]
modId="blockhistory"
version="${file.jarVersion}"
displayName="Block History"
displayURL="https://www.curseforge.com/minecraft/mc-mods/block-history"
authors="Mrbysco"
description='''
Just storing block interactions
'''