modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Mrbysco/BlockHistory/issues"
license="MIT"

[[mods]]
modId="blockhistory"
version="${file.jarVersion}"
displayName="Block History"
displayURL="https://www.curseforge.com/minecraft/mc-mods/block-history"
authors="Mrbysco"
description='''
Just storing block interactions
'''
[[dependencies.blockhistory]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"