modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Mrbysco/BlockHistory/issues"
license="MIT"

[[mods]]
modId="blockhistory"
version="${file.jarVersion}"
displayName="Block History"
displayURL="https://www.curseforge.com/minecraft/mc-mods/block-history"
authors="Mrbysco"
description='''
Just storing block interactions
'''
[[dependencies.blockhistory]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.blockhistory]]
modId="forge"
mandatory=true
versionRange="[41.0.94,)"
ordering="NONE"
side="BOTH"