modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/BlockHistory/issues"
license="MIT"

[[mods]]
modId="blockhistory"
version="${file.jarVersion}"
displayName="Block History"
displayURL="https://www.curseforge.com/minecraft/mc-mods/block-history"
authors="Mrbysco"
description='''
Just storing block interactions
'''
[[dependencies.blockhistory]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"