modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/BlockHistory/issues"
license="MIT"

[[mods]]
modId="blockhistory"
version="${file.jarVersion}"
displayName="Block History"
displayURL="https://www.curseforge.com/minecraft/mc-mods/block-history"
authors="Mrbysco"
description='''
Just storing block interactions
'''
[[dependencies.blockhistory]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21.4,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.blockhistory]]
modId="neoforge"
type="required"
versionRange="[21.4.0-beta,)"
ordering="NONE"
side="BOTH"